In [ ]:
# !mkdir deblurnerf_dataset

In [ ]:
# !git clone https://github.com/limacv/Deblur-NeRF.git

Cloning into 'Deblur-NeRF'...
remote: Enumerating objects: 141, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 141 (delta 64), reused 57 (delta 57), pack-reused 69
Receiving objects: 100% (141/141), 63.89 KiB | 1.77 MiB/s, done.
Resolving deltas: 100% (81/81), done.


In [ ]:
# !pip3 install -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 3.9 MB/s eta 0:00:00


In [ ]:
from google.colab import drive
import os

WORK_DRIVE = '/content/drive'
WORK_AREA = WORK_DRIVE + '/MyDrive/BDRP/BDRP'

drive.mount(WORK_DRIVE)
os.chdir(WORK_AREA)

Mounted at /content/drive


In [ ]:
os.chdir(WORK_AREA+'/Deblur-NeRF')

In [ ]:
# os.sys.path

['/content',
 '/env/python',
 '/usr/lib/python310.zip',
 '/usr/lib/python3.10',
 '/usr/lib/python3.10/lib-dynload',
 '',
 '/usr/local/lib/python3.10/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.10/dist-packages/IPython/extensions',
 '/root/.ipython']

In [ ]:
# t = [os.path.join('./model', 'blurball1_full_woprior_wodepth', f) for f in sorted(os.listdir(os.path.join('./model', 'blurball1_full_woprior_wodepth'))) if
#                  '.tar' in f]

In [ ]:
# t ## make sure that the desired pretrained weights exists

['./model/blurball1_full_woprior_wodepth/200000.tar']

Run Deblur-NeRF using pretrained weights

In [ ]:
!python3 run_nerf.py --config configs/blurball/tx_blurball_full_crf.txt --render_only

/usr/local/lib/python3.10/dist-packages/torch/__init__.py:614: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:451.)
  _C._set_default_tensor_type(t)
Loaded image data (400, 600, 3, 27) [400.         600.         421.10768103]
Loaded ./deblurnerf_dataset/real_camera_motion_blur/blurball 10.847889476359242 29.73636276710649
recentered (3, 5)
[[ 1.0000000e+00  6.4581251e-09  1.3332152e-08  1.1037897e-09]
 [-6.4581251e-09  1.0000000e+00 -4.0485069e-09 -2.7594742e-09]
 [-1.3332152e-08  4.0485069e-09  1.0000000e+00 -3.8632639e-09]]
Data:
(27, 3, 5) (27, 400, 600, 3) (27, 2)
HOLDOUT view is 6
Loaded llff (27, 400, 600, 3) (120, 3, 5) [400.      600.      421.10767] ./deblurnerf_dataset/real_camera_motion_blur/blurball
LLFF holdout, 7
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['./model/blurball1_full_crf_woprior_w